build:
	tsc

dist-clean:
	-@rm -rf dist/
	-@mkdir dist
	@cp index.html dist/

pack: dist-clean
	webpack --mode=production

dev-pack: dist-clean
	webpack --mode=development

zip: pack
	cd dist; zip plugin.zip index.html main.js

dev-zip: dev-pack
	cd dist; zip plugin.zip index.html main.js

upload:
	pluginmgr --filename dist/plugin.zip upload Iframe

upload-debug:
	pluginmgr --filename dist/plugin.zip upload  --verbose true --debug true --save true  Iframe